In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('adult.csv')
df.head()

,39,State-gov,77516,Bachelors,13,Never-married,Adm-clerical,Not-in-family,White,Male,2174,0,40,United-States,<=50K
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [3]:
col = ['age','workclass','fnlwgt','education','education-num','marital-status','occupation','relationship','race','sex','capital-gain','capital-loss','hours-per-week','native-country','target']

In [4]:
df.columns=col
df.head()

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K

In [6]:
df.isnull().sum()

age               0
workclass         0
fnlwgt            0
education         0
education-num     0
marital-status    0
occupation        0
relationship      0
race              0
sex               0
capital-gain      0
capital-loss      0
hours-per-week    0
native-country    0
target            0
dtype: int64

**Creating Subsets**

In [9]:
df['sex'].unique()

array([' Male', ' Female'], dtype=object)

In [10]:
s1 = df[df['sex']==' Male']
s1

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K
32553,53,Private,321865,Masters,14,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,40,United-States,>50K
32554,22,Private,310152,Some-college,10,Never-married,Protective-serv,Not-in-family,White,Male,0,0,40,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K

In [11]:
s2 = df[df['sex']==' Female']
s2

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32545,37,Private,198216,Assoc-acdm,12,Divorced,Tech-support,Not-in-family,White,Female,0,0,40,United-States,<=50K
32548,43,State-gov,255835,Some-college,10,Divorced,Adm-clerical,Other-relative,White,Female,0,0,40,United-States,<=50K
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [12]:
df['race'].unique()

array([' White', ' Black', ' Asian-Pac-Islander', ' Amer-Indian-Eskimo',
       ' Other'], dtype=object)

In [13]:
df['native-country'].unique()

array([' United-States', ' Cuba', ' Jamaica', ' India', ' ?', ' Mexico',
       ' South', ' Puerto-Rico', ' Honduras', ' England', ' Canada',
       ' Germany', ' Iran', ' Philippines', ' Italy', ' Poland',
       ' Columbia', ' Cambodia', ' Thailand', ' Ecuador', ' Laos',
       ' Taiwan', ' Haiti', ' Portugal', ' Dominican-Republic',
       ' El-Salvador', ' France', ' Guatemala', ' China', ' Japan',
       ' Yugoslavia', ' Peru', ' Outlying-US(Guam-USVI-etc)', ' Scotland',
       ' Trinadad&Tobago', ' Greece', ' Nicaragua', ' Vietnam', ' Hong',
       ' Ireland', ' Hungary', ' Holand-Netherlands'], dtype=object)

In [14]:
s3=df[df['race']==' White']
s3

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32555,27,Private,257302,Assoc-acdm,12,Married-civ-spouse,Tech-support,Wife,White,Female,0,0,38,United-States,<=50K
32556,40,Private,154374,HS-grad,9,Married-civ-spouse,Machine-op-inspct,Husband,White,Male,0,0,40,United-States,>50K
32557,58,Private,151910,HS-grad,9,Widowed,Adm-clerical,Unmarried,White,Female,0,0,40,United-States,<=50K
32558,22,Private,201490,HS-grad,9,Never-married,Adm-clerical,Own-child,White,Male,0,0,20,United-States,<=50K
32559,52,Self-emp-inc,287927,HS-grad,9,Married-civ-spouse,Exec-managerial,Wife,White,Female,15024,0,40,United-States,>50K

In [15]:
s4=df[df['race']==' Black']
s4

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
9,37,Private,280464,Some-college,10,Married-civ-spouse,Exec-managerial,Husband,Black,Male,0,0,80,United-States,>50K
12,32,Private,205019,Assoc-acdm,12,Never-married,Sales,Not-in-family,Black,Male,0,0,50,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32520,33,Private,273243,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Black,Male,0,0,40,United-States,<=50K
32534,22,Private,325033,12th,8,Never-married,Protective-serv,Own-child,Black,Male,0,0,35,United-States,<=50K
32536,30,Private,345898,HS-grad,9,Never-married,Craft-repair,Not-in-family,Black,Male,0,0,46,United-States,<=50K
32537,38,Private,139180,Bachelors,13,Divorced,Prof-specialty,Unmarried,Black,Female,15020,0,45,United-States,>50K
32540,41,?,202822,HS-grad,9,Separated,?,Not-in-family,Black,Female,0,0,32,United-States,<=50K

In [16]:
s5=df[df['race']== ' Asian-Pac-Islander']
s5

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
10,30,State-gov,141297,Bachelors,13,Married-civ-spouse,Prof-specialty,Husband,Asian-Pac-Islander,Male,0,0,40,India,>50K
13,40,Private,121772,Assoc-voc,11,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,?,>50K
26,54,?,180211,Some-college,10,Married-civ-spouse,?,Husband,Asian-Pac-Islander,Male,0,0,60,South,>50K
92,30,Private,117747,HS-grad,9,Married-civ-spouse,Sales,Wife,Asian-Pac-Islander,Female,0,1573,35,?,<=50K
138,49,Private,81973,Some-college,10,Married-civ-spouse,Craft-repair,Husband,Asian-Pac-Islander,Male,0,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32456,33,Private,139057,Masters,14,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0,0,50,United-States,>50K
32485,24,Private,216984,Some-college,10,Married-civ-spouse,Other-service,Own-child,Asian-Pac-Islander,Female,0,0,35,United-States,<=50K
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K

In [17]:
s6=df[df['race']== ' Amer-Indian-Eskimo']
s6

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
14,34,Private,245487,7th-8th,4,Married-civ-spouse,Transport-moving,Husband,Amer-Indian-Eskimo,Male,0,0,45,Mexico,<=50K
211,35,Private,153790,Some-college,10,Never-married,Sales,Not-in-family,Amer-Indian-Eskimo,Female,0,0,40,United-States,<=50K
225,60,?,24215,10th,6,Divorced,?,Not-in-family,Amer-Indian-Eskimo,Female,0,0,10,United-States,<=50K
446,51,Private,56915,HS-grad,9,Married-civ-spouse,Craft-repair,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
515,25,Private,267044,Some-college,10,Never-married,Adm-clerical,Not-in-family,Amer-Indian-Eskimo,Female,0,0,20,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32230,44,Private,33105,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32241,33,Private,356015,HS-grad,9,Separated,Craft-repair,Not-in-family,Amer-Indian-Eskimo,Male,0,0,35,Hong,<=50K
32248,35,Private,91839,Bachelors,13,Married-civ-spouse,Other-service,Husband,Amer-Indian-Eskimo,Male,7688,0,20,United-States,>50K
32424,23,Private,180771,1st-4th,2,Married-civ-spouse,Machine-op-inspct,Wife,Amer-Indian-Eskimo,Female,0,0,35,Mexico,<=50K
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K

In [18]:
s7=df[df['race']== ' Other']
s7

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
49,25,Private,32275,Some-college,10,Married-civ-spouse,Exec-managerial,Wife,Other,Female,0,0,40,United-States,<=50K
232,33,Private,110978,Some-college,10,Divorced,Craft-repair,Other-relative,Other,Female,0,0,40,United-States,<=50K
355,65,Private,161400,11th,7,Widowed,Other-service,Unmarried,Other,Male,0,0,40,United-States,<=50K
403,28,Private,166481,7th-8th,4,Married-civ-spouse,Handlers-cleaners,Husband,Other,Male,0,2179,40,Puerto-Rico,<=50K
529,44,Private,109339,11th,7,Divorced,Machine-op-inspct,Unmarried,Other,Female,0,0,46,Puerto-Rico,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32074,27,?,147638,Masters,14,Never-married,?,Not-in-family,Other,Female,0,0,40,Japan,<=50K
32231,30,Private,215441,Some-college,10,Never-married,Adm-clerical,Not-in-family,Other,Male,0,0,40,?,<=50K
32262,27,Private,176761,HS-grad,9,Never-married,Craft-repair,Other-relative,Other,Male,0,0,40,Nicaragua,<=50K
32431,36,Private,208068,Preschool,1,Divorced,Other-service,Not-in-family,Other,Male,0,0,72,Mexico,<=50K
32543,31,Private,199655,Masters,14,Divorced,Other-service,Not-in-family,Other,Female,0,0,30,United-States,<=50K

**Merging**

In [22]:
m1 = pd.concat([s1,s5])
m1

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
0,50,Self-emp-not-inc,83311,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,13,United-States,<=50K
1,38,Private,215646,HS-grad,9,Divorced,Handlers-cleaners,Not-in-family,White,Male,0,0,40,United-States,<=50K
2,53,Private,234721,11th,7,Married-civ-spouse,Handlers-cleaners,Husband,Black,Male,0,0,40,United-States,<=50K
6,52,Self-emp-not-inc,209642,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,White,Male,0,0,45,United-States,>50K
8,42,Private,159449,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,White,Male,5178,0,40,United-States,>50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32456,33,Private,139057,Masters,14,Married-civ-spouse,Tech-support,Husband,Asian-Pac-Islander,Male,0,0,50,United-States,>50K
32485,24,Private,216984,Some-college,10,Married-civ-spouse,Other-service,Own-child,Asian-Pac-Islander,Female,0,0,35,United-States,<=50K
32530,30,?,33811,Bachelors,13,Never-married,?,Not-in-family,Asian-Pac-Islander,Female,0,0,99,United-States,<=50K
32532,54,Private,337992,Bachelors,13,Married-civ-spouse,Exec-managerial,Husband,Asian-Pac-Islander,Male,0,0,50,Japan,>50K
32552,32,Private,116138,Masters,14,Never-married,Tech-support,Not-in-family,Asian-Pac-Islander,Male,0,0,11,Taiwan,<=50K

In [23]:
m2 = pd.concat([s2,s6])
m2

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
3,28,Private,338409,Bachelors,13,Married-civ-spouse,Prof-specialty,Wife,Black,Female,0,0,40,Cuba,<=50K
4,37,Private,284582,Masters,14,Married-civ-spouse,Exec-managerial,Wife,White,Female,0,0,40,United-States,<=50K
5,49,Private,160187,9th,5,Married-spouse-absent,Other-service,Not-in-family,Black,Female,0,0,16,Jamaica,<=50K
7,31,Private,45781,Masters,14,Never-married,Prof-specialty,Not-in-family,White,Female,14084,0,50,United-States,>50K
11,23,Private,122272,Bachelors,13,Never-married,Adm-clerical,Own-child,White,Female,0,0,30,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32230,44,Private,33105,HS-grad,9,Married-civ-spouse,Exec-managerial,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K
32241,33,Private,356015,HS-grad,9,Separated,Craft-repair,Not-in-family,Amer-Indian-Eskimo,Male,0,0,35,Hong,<=50K
32248,35,Private,91839,Bachelors,13,Married-civ-spouse,Other-service,Husband,Amer-Indian-Eskimo,Male,7688,0,20,United-States,>50K
32424,23,Private,180771,1st-4th,2,Married-civ-spouse,Machine-op-inspct,Wife,Amer-Indian-Eskimo,Female,0,0,35,Mexico,<=50K
32550,32,Private,34066,10th,6,Married-civ-spouse,Handlers-cleaners,Husband,Amer-Indian-Eskimo,Male,0,0,40,United-States,<=50K

**Sort**

In [24]:
df_sort = df.sort_values('age')
df_sort

,age,workclass,fnlwgt,education,education-num,marital-status,occupation,relationship,race,sex,capital-gain,capital-loss,hours-per-week,native-country,target
15541,17,?,112942,10th,6,Never-married,?,Own-child,White,Male,0,0,40,United-States,<=50K
26089,17,Self-emp-not-inc,174120,12th,8,Never-married,Handlers-cleaners,Own-child,White,Male,0,0,15,United-States,<=50K
22495,17,Private,118792,11th,7,Never-married,Sales,Own-child,White,Female,0,0,9,United-States,<=50K
22856,17,Local-gov,340043,12th,8,Never-married,Adm-clerical,Own-child,White,Female,0,0,12,United-States,<=50K
12980,17,?,262196,10th,6,Never-married,?,Own-child,White,Male,0,0,8,United-States,<=50K
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11511,90,Private,87285,HS-grad,9,Never-married,Other-service,Own-child,White,Female,0,0,24,United-States,<=50K
12450,90,?,225063,Some-college,10,Never-married,?,Own-child,Asian-Pac-Islander,Male,0,0,10,South,<=50K
6623,90,Private,313986,11th,7,Married-civ-spouse,Craft-repair,Husband,White,Male,0,0,40,United-States,<=50K
18831,90,Private,115306,Masters,14,Never-married,Exec-managerial,Own-child,White,Female,0,0,40,United-States,<=50K
8805,90,Private,87372,Prof-school,15,Married-civ-spouse,Prof-specialty,Husband,White,Male,20051,0,72,United-States,>50K

**Transpose**

In [25]:
df_transpose = df.transpose()

In [26]:
df_transpose

,0,1,2,3,4,5,6,7,8,9,...,32550,32551,32552,32553,32554,32555,32556,32557,32558,32559
age,50,38,53,28,37,49,52,31,42,37,...,32,43,32,53,22,27,40,58,22,52
workclass,Self-emp-not-inc,Private,Private,Private,Private,Private,Self-emp-not-inc,Private,Private,Private,...,Private,Private,Private,Private,Private,Private,Private,Private,Private,Self-emp-inc
fnlwgt,83311,215646,234721,338409,284582,160187,209642,45781,159449,280464,...,34066,84661,116138,321865,310152,257302,154374,151910,201490,287927
education,Bachelors,HS-grad,11th,Bachelors,Masters,9th,HS-grad,Masters,Bachelors,Some-college,...,10th,Assoc-voc,Masters,Masters,Some-college,Assoc-acdm,HS-grad,HS-grad,HS-grad,HS-grad
education-num,13,9,7,13,14,5,9,14,13,10,...,6,11,14,14,10,12,9,9,9,9
marital-status,Married-civ-spouse,Divorced,Married-civ-spouse,Married-civ-spouse,Married-civ-spouse,Married-spouse-absent,Married-civ-spouse,Never-married,Married-civ-spouse,Married-civ-spouse,...,Married-civ-spouse,Married-civ-spouse,Never-married,Married-civ-spouse,Never-married,Married-civ-spouse,Married-civ-spouse,Widowed,Never-married,Married-civ-spouse
occupation,Exec-managerial,Handlers-cleaners,Handlers-cleaners,Prof-specialty,Exec-managerial,Other-service,Exec-managerial,Prof-specialty,Exec-managerial,Exec-managerial,...,Handlers-cleaners,Sales,Tech-support,Exec-managerial,Protective-serv,Tech-support,Machine-op-inspct,Adm-clerical,Adm-clerical,Exec-managerial
relationship,Husband,Not-in-family,Husband,Wife,Wife,Not-in-family,Husband,Not-in-family,Husband,Husband,...,Husband,Husband,Not-in-family,Husband,Not-in-family,Wife,Husband,Unmarried,Own-child,Wife
race,White,White,Black,Black,White,Black,White,White,White,Black,...,Amer-Indian-Eskimo,White,Asian-Pac-Islander,White,White,White,White,White,White,White
sex,Male,Male,Male,Female,Female,Female,Male,Female,Male,Male,...,Male,Male,Male,Male,Male,Female,Male,Female,Male,Female
capital-gain,0,0,0,0,0,0,0,14084,5178,0,...,0,0,0,0,0,0,0,0,0,15024
capital-loss,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
hours-per-week,13,40,40,40,40,16,45,50,40,80,...,40,45,11,40,40,38,40,40,20,40
native-country,United-States,United-States,United-States,Cuba,United-States,Jamaica,United-States,United-States,United-States,United-States,...,United-States,United-States,Taiwan,United-States,United-States,United-States,United-States,United-States,United-States,United-States
target,<=50K,<=50K,<=50K,<=50K,<=50K,<=50K,>50K,>50K,>50K,>50K,...,<=50K,<=50K,<=50K,>50K,<=50K,<=50K,>50K,<=50K,<=50K,>50K

**Melt**

In [27]:
df_melt = pd.melt(df,id_vars=['workclass','education'],var_name='Metric',value_name='value')
df_melt

                workclass    education  Metric   value
0        Self-emp-not-inc    Bachelors     age      50
1                 Private      HS-grad     age      38
2                 Private         11th     age      53
3                 Private    Bachelors     age      28
4                 Private      Masters     age      37
...                   ...          ...     ...     ...
423275            Private   Assoc-acdm  target   <=50K
423276            Private      HS-grad  target    >50K
423277            Private      HS-grad  target   <=50K
423278            Private      HS-grad  target   <=50K
423279       Self-emp-inc      HS-grad  target    >50K

[423280 rows x 4 columns]

**Casting**

In [29]:
df_cast = pd.pivot_table(df,index=['workclass','occupation'],values=['hours-per-week'])
df_cast

                                 hours-per-week
workclass    occupation
 ?            ?                       31.919390
 Federal-gov  Adm-clerical            40.154574
              Armed-Forces            40.666667
              Craft-repair            40.781250
              Exec-managerial         42.572222
...                                         ...
 Without-pay  Farming-fishing         36.666667
              Handlers-cleaners       40.000000
              Machine-op-inspct       25.000000
              Other-service           55.000000
              Transport-moving        20.000000

[83 rows x 1 columns]